CREATE TABLE cliente
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cpf           VARCHAR(255)                            NOT NULL,
    nome          VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    telefone      VARCHAR(255)                            NOT NULL,
    data_cadastro TIMESTAMP                               NOT NULL,
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

CREATE TABLE comanda
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo_comanda VARCHAR(255)                            NOT NULL,
    data_criacao   TIMESTAMP                               NOT NULL,
    data_pagamento TIMESTAMP,
    gasto_total    DECIMAL,
    cliente_id     BIGINT,
    folha_id       BIGINT,
    CONSTRAINT pk_comanda PRIMARY KEY (id)
);

CREATE TABLE comanda_gastos
(
    comanda_id BIGINT NOT NULL,
    gastos_id  BIGINT NOT NULL
);

CREATE TABLE folha
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_abertura   date                                    NOT NULL,
    data_fechamento date,
    fechado         BOOLEAN,
    CONSTRAINT pk_folha PRIMARY KEY (id)
);

CREATE TABLE gasto
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id    BIGINT,
    valor_pago DECIMAL                                 NOT NULL,
    comanda_id BIGINT,
    CONSTRAINT pk_gasto PRIMARY KEY (id)
);

CREATE TABLE item
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome  VARCHAR(255)                            NOT NULL,
    preco DECIMAL                                 NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

ALTER TABLE cliente
    ADD CONSTRAINT uc_cliente_cpf UNIQUE (cpf);

ALTER TABLE comanda
    ADD CONSTRAINT uc_comanda_codigo_comanda UNIQUE (codigo_comanda);

ALTER TABLE comanda_gastos
    ADD CONSTRAINT uc_comanda_gastos_gastos UNIQUE (gastos_id);

ALTER TABLE comanda
    ADD CONSTRAINT FK_COMANDA_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES cliente (id);

ALTER TABLE comanda
    ADD CONSTRAINT FK_COMANDA_ON_FOLHA FOREIGN KEY (folha_id) REFERENCES folha (id);

ALTER TABLE gasto
    ADD CONSTRAINT FK_GASTO_ON_COMANDA FOREIGN KEY (comanda_id) REFERENCES comanda (id);

ALTER TABLE gasto
    ADD CONSTRAINT FK_GASTO_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);

ALTER TABLE comanda_gastos
    ADD CONSTRAINT fk_comgas_on_comanda FOREIGN KEY (comanda_id) REFERENCES comanda (id);

ALTER TABLE comanda_gastos
    ADD CONSTRAINT fk_comgas_on_gasto FOREIGN KEY (gastos_id) REFERENCES gasto (id);